export const API_PREFIX = 'api/v1';

export const DEFAULT_MAX_REQUEST_ITEMS_LIMIT = 100;
export const DEFAULT_REQUEST_ITEMS_LIMIT = 20;
export const DEFAULT_REQUEST_ITEMS_OFFSET = 0;

export const DEFAULT_TRANSACTION_STATS_DAYS = 30;
