---
- name: Cleanup old docker images
  shell: "(docker system prune -a -f > /dev/null &)"
  async: 10
  poll: 0

- name: Setup docker-compose.yml
  template: 
    src: "docker-compose.yml.j2"
    dest: "{{ SERVER_MAIN_DIR }}/docker-compose.yml"
    force: yes
  register: docker_service_update

- name: Env Server
  template: 
    src: "fio-server.env.j2"
    dest: "{{ SERVER_MAIN_DIR }}/config/fio-server.env"
    force: yes

- name: Env Client
  template: 
    src: "fio-client.env.j2"
    dest: "{{ SERVER_MAIN_DIR }}/config/fio-client.env"
    force: yes

- name: Start/update services
  shell:
    cmd: docker-compose up -d
    chdir: "{{ SERVER_MAIN_DIR }}"
  register: output
  debugger: on_failed

- debug:
    var: output
  when: docker_service_update.changed
