on:
  push:
    branches: [ pipeline ]
  pull_request:
    branches: [ pipeline ]

env: 
  AWS_REGION_DEV : "us-west-2"
  ECR_REPOSITORY_CLIENT: "fio-relic-explorer-client"
  ECR_REPOSITORY_SERVER: "fio-relic-explorer-server"
  
permissions:
      id-token: write
      contents: read
jobs:
  Deploy-fio-relic:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::916790350352:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION_DEV }}
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
      - name: Fetch secret from AWS Parameter Store
        run: |
          SSH_HOST=$(aws ssm get-parameter --name "/fio-relic/dev/SSH_HOST" --with-decryption --query "Parameter.Value" --output text)
          echo "SSH_HOST=${SSH_HOST}" >> $GITHUB_ENV
          aws ssm get-parameter --name "/fio-relic/dev/ssh_key" --with-decryption --query "Parameter.Value" --output text > ssh_key
          chmod 600 ssh_key
      - name: SSH to EC2 and run command
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh_key root@$SSH_HOST "\
            aws ecr get-login-password --region us-west-2 | \
            docker login --username AWS --password-stdin 916790350352.dkr.ecr.us-west-2.amazonaws.com/fio-relic-explorer-client, \
            docker login --username AWS --password-stdin 916790350352.dkr.ecr.us-west-2.amazonaws.com/fio-relic-explorer-server"
