on:
  push:
    branches: [ devops ]
  pull_request:
    branches: [ devops ]

env: 
  AWS_REGION : "us-west-2"
  
permissions:
      id-token: write
      contents: read
jobs:
  Deploy-fio-relic:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::916790350352:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
      - name: Fetch secret from AWS Parameter Store
        run: |
          DB_NAME=$(aws ssm get-parameter --name "/fio-relic/dev/DB_NAME" --with-decryption --query "Parameter.Value" --output text)
          echo "SECRET_VALUE=${DB_NAME}" >> $GITHUB_ENV
          DB_HOST=$(aws ssm get-parameter --name "/fio-relic/dev/DB_HOST" --with-decryption --query "Parameter.Value" --output text)
          echo "SECRET_VALUE=${DB_HOST}" >> $GITHUB_ENV
          DB_PASSWORD=$(aws ssm get-parameter --name "/fio-relic/dev/DB_PASSWORD" --with-decryption --query "Parameter.Value" --output text)
          echo "SECRET_VALUE=${DB_PASSWORD}" >> $GITHUB_ENV
          DB_PORT=$(aws ssm get-parameter --name "/fio-relic/dev/DB_PORT" --with-decryption --query "Parameter.Value" --output text)
          echo "SECRET_VALUE=${DB_PORT}" >> $GITHUB_ENV
          DB_SSL=$(aws ssm get-parameter --name "/fio-relic/dev/DB_SSL" --with-decryption --query "Parameter.Value" --output text)
          echo "SECRET_VALUE=${DB_SSL}" >> $GITHUB_ENV
          DB_USER=$(aws ssm get-parameter --name "/fio-relic/dev/DB_USER" --with-decryption --query "Parameter.Value" --output text)
          echo "SECRET_VALUE=${DB_USER}" >> $GITHUB_ENV
          HOST=$(aws ssm get-parameter --name "/fio-relic/dev/HOST" --with-decryption --query "Parameter.Value" --output text)
          echo "SECRET_VALUE=${HOST}" >> $GITHUB_ENV
          NODE_ENV=$(aws ssm get-parameter --name "/fio-relic/dev/NODE_ENV" --with-decryption --query "Parameter.Value" --output text)
          echo "SECRET_VALUE=${NODE_ENV}" >> $GITHUB_ENV
          PORT=$(aws ssm get-parameter --name "/fio-relic/dev/PORT" --with-decryption --query "Parameter.Value" --output text)
          echo "SECRET_VALUE=${PORT}" >> $GITHUB_ENV
      - name: Use the secret
        run: |
         echo "Secret value is $PORT"
         echo "Secret value2 is $HOST"
      - name: Fetch secret from AWS Parameter Store2
        run: |
          SECRET_VALUE=$(aws ssm get-parameter --name "/fio-relic/dev/DB_NAME" --with-decryption --query "Parameter.Value" --output text)
          echo "SECRET_VALUE=${SECRET_VALUE}" >> $GITHUB_ENV
      - name: Use the secret
        run: echo "Secret value is $SECRET_VALUE"
